<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pemesanan_model extends CI_Model
{

    public $table = 'pemesanan';
    public $id = 'pemesanan.idpemesanan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->from($this->table)->join('barang', 'pemesanan.id_barang=barang.id_barang')->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->from($this->table)->join('barang', 'pemesanan.id_barang=barang.id_barang')->get()->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('barang.id_barang', $q);
		$this->db->or_like('barang.nama_barang', $q);	
		$this->db->from($this->table)->join('barang', 'pemesanan.id_barang=barang.id_barang');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('barang.id_barang', $q);
		$this->db->or_like('barang.nama_barang', $q);
		
		$this->db->limit($limit, $start);
        return $this->db->from($this->table)->join('barang', 'pemesanan.id_barang=barang.id_barang')->get()->result();
    }
}

/* End of file Barang_model.php */
/* Location: ./application/models/Barang_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-26 13:57:25 */
/* http://harviacode.com */